name = "hutsgroupsite"
compatibility_date = "2026-03-12"
pages_build_output_dir = "."

[vars]
TURNSTILE_SITE_KEY = "0X4AAAAAACpsp0aB-mt8GgBM"

[[d1_databases]]
binding = "CONTACTS_DB"
database_name = "contacts"
database_id = "e6b353c8-feb7-4b5c-b60c-6a56864fecbb"
